#!/usr/bin/env python3
"""Build docs/PROMPTS.md from VIDA-GEO's committed prompt sources."""
from __future__ import annotations

import ast
import json
from pathlib import Path
import runpy


ROOT = Path(__file__).resolve().parents[1]
PROMPTS_ROOT = ROOT / "configs" / "prompts"
OUTPUT = ROOT / "docs" / "PROMPTS.md"
GSV_STAGES = (
    "planner",
    "planner_epoch",
    "suggestion_gemini",
    "suggestion_flux",
    "mask_qc",
    "edit_qc",
)
SATELLITE_SHARED_STAGES = ("planner", "planner_epoch")
SATELLITE_SPECIALIZED_STAGES = (
    "suggestion_gemini",
    "suggestion_flux",
    "mask_qc",
    "edit_qc",
)


def fenced(text: str, language: str = "text") -> str:
    return f"```{language}\n{text.rstrip()}\n```"


def markdown_details(summary: str, body: str) -> str:
    return (
        "<details>\n"
        f"<summary>{summary}</summary>\n\n"
        f"{body.rstrip()}\n\n"
        "</details>"
    )


def literal_string(node: ast.AST) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "strip"
    ):
        return literal_string(node.func.value).strip()
    raise ValueError(f"Unsupported string expression: {ast.dump(node)}")


def policy_system_prompt() -> str:
    source = ROOT / "vida_geo" / "agents" / "policy.py"
    tree = ast.parse(source.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "_SYSTEM_PROMPT"
            for target in node.targets
        ):
            return literal_string(node.value)
    raise RuntimeError(f"_SYSTEM_PROMPT not found in {source}")


GEMINI_MASKED = """You will receive two images:
1) The original image to edit.
2) A mask. White pixels indicate the ONLY region you are allowed to change. Black pixels must remain EXACTLY the same.

Task: {suggested_edit_prompt}

Rules:
- ONLY modify pixels inside the white mask region.
- Do not change anything outside the white region.
- Blend naturally with the scene.
- Do not add text, labels, watermarks, or borders."""

GEMINI_MASKLESS = """Edit this image according to the following instruction:

{suggested_edit_prompt}

Rules:
- Keep everything else the same.
- Blend naturally with the scene.
- Do not add text, labels, watermarks, or borders."""

GEMINI_REMOVE = """Remove the {region_label} from the highlighted/masked area. Fill naturally with the surrounding background — match textures, lighting, and perspective seamlessly."""


def judge_spec() -> dict:
    """Load the tracked, self-contained judge specification without invoking main."""
    namespace = runpy.run_path(str(ROOT / "llm_judge" / "qwen3vl_evaluate.py"))
    return {
        "policy_prompt": namespace["POLICY_PRESERVATION_PROMPT"],
        "revised_prompt": namespace["JUDGE_PROMPT"],
        "schema": namespace["schema"](),
    }


def prompt_details(group: str, stage: str, summary: str | None = None) -> str:
    path = PROMPTS_ROOT / group / f"{stage}.txt"
    source = f"../configs/prompts/{group}/{stage}.txt"
    label = summary or f"<code>{stage}</code>"
    return markdown_details(
        f"{label} - <a href=\"{source}\">source</a>",
        fenced(path.read_text(encoding="utf-8")),
    )


def build() -> str:
    judge = judge_spec()
    parts = [
        "# VIDA-GEO Pipeline Prompt Reference",
        "",
        "This page documents the complete stable prompts used by the VIDA-GEO "
        "agent pipeline and its LLM-as-judge evaluation. Prompts are reproduced "
        "verbatim from their tracked sources and can be expanded below. Dynamic "
        "scene data, region history, scores, and constraints are appended at "
        "runtime and are intentionally not repeated as placeholder templates.",
        "",
        "> This file is generated by `python scripts/build_prompt_reference.py`. "
        "Edit the source templates or generator rather than editing this page directly.",
        "",
        "## API-call inventory",
        "",
        "| Stage | API/model role | Images supplied | Prompt source |",
        "|---|---|---:|---|",
        "| Baseline and candidate scoring | Domain scorer service | 1 | No natural-language prompt |",
        "| Initial planning | Reasoning VLM | 1 | Domain `planner.txt` plus dynamic user message |",
        "| Later-epoch planning | Reasoning VLM | 1 | Domain `planner_epoch.txt` plus attempt history |",
        "| Policy review | Reasoning VLM | 1 | Shared policy system prompt plus all planned regions |",
        "| Text segmentation | LISAt or SAM3 | 1 | Planner-derived concrete `seg_keyword` and synonyms |",
        "| SAM fallback | SAM | 1 | Point coordinates and labels only; no text prompt |",
        "| Generation suggestion | Reasoning VLM | 1 or 2 | Domain `suggestion_gemini.txt` or `suggestion_flux.txt` |",
        "| Gemini generation | Gemini image editor | 1 or 2 | Suggested edit wrapped in masked or maskless instructions |",
        "| FLUX generation | FLUX Fill service | image + mask | Suggested visual-result prompt is passed directly |",
        "| Mask QC | Reasoning VLM | original + mask | Domain `mask_qc.txt` plus target description |",
        "| Edit QC | Reasoning VLM | original + edit [+ mask] | Domain `edit_qc.txt` plus edit and preservation constraints |",
        "",
        "All reasoning calls use the shared OpenRouter transport in "
        "[`vida_geo/llm/openrouter.py`](../vida_geo/llm/openrouter.py). "
        "Image generation uses [`vida_geo/tools/gemini.py`](../vida_geo/tools/gemini.py) "
        "or the FLUX service.",
        "",
        "### Text-segmentation requests",
        "",
        "LISAt and SAM3 receive the planner's refined one- or two-word "
        "`seg_keyword` (for example, `road`, `parking lot`, `street lamp`, or "
        "`tree canopy`). VIDA-GEO may retry up to four concrete synonym variants. "
        "This request contains no separate system prompt.",
        "",
        "## Shared policy prompt",
        "",
        "Source: [`vida_geo/agents/policy.py`](../vida_geo/agents/policy.py)",
        "",
        markdown_details(
            "Policy system prompt (verbatim)",
            fenced(policy_system_prompt()),
        ),
        "",
        "## Image-editor request wrappers",
        "",
        "The suggestion agent first produces `{suggested_edit_prompt}` using one "
        "of the domain templates below. The selected prompt is then wrapped as follows.",
        "",
        markdown_details("Gemini masked-edit instruction", fenced(GEMINI_MASKED)),
        "",
        markdown_details("Gemini maskless instruction", fenced(GEMINI_MASKLESS)),
        "",
        markdown_details("Gemini removal instruction (GSV only)", fenced(GEMINI_REMOVE)),
        "",
        "FLUX receives the selected visual-result prompt directly, along with the "
        "cropped ROI image and mask.",
        "",
        "## Stable domain system prompts",
        "",
        "Template variables are substituted at runtime:",
        "",
        "- `$metric`: the domain score key.",
        "- `$direction`: `increase` or `reduce`, derived from the registry and goal.",
        "- `$metric_description` and `$edit_examples`: domain hints from "
        "[`configs/domains.yaml`](../configs/domains.yaml).",
        "- `$score_ctx`, `$previous_attempts`, `$tried_coords`, and `$phase_ctx`: "
        "current-score and orchestration history.",
        "",
        "### Google Street View domains",
        "",
    ]

    for stage in GSV_STAGES:
        parts.extend([prompt_details("gsv", stage), ""])

    parts.extend([
        "### Satellite domains: shared planning prompts",
        "",
        "Road safety and greenery use byte-identical initial and later-epoch "
        "planner prompts. They are shown once here; the runtime metric, direction, "
        "description, examples, scores, and history supply the domain context.",
        "",
    ])
    for stage in SATELLITE_SHARED_STAGES:
        road_path = PROMPTS_ROOT / "road_safety" / f"{stage}.txt"
        green_path = PROMPTS_ROOT / "greenery" / f"{stage}.txt"
        road_text = road_path.read_text(encoding="utf-8")
        green_text = green_path.read_text(encoding="utf-8")
        if road_text != green_text:
            raise RuntimeError(
                f"Satellite {stage} prompts are no longer identical; document them separately"
            )
        parts.extend([
            markdown_details(
                f"<code>{stage}</code> - "
                f"<a href=\"../configs/prompts/road_safety/{stage}.txt\">road-safety source</a>, "
                f"<a href=\"../configs/prompts/greenery/{stage}.txt\">greenery source</a>",
                fenced(road_text),
            ),
            "",
        ])

    for group, label in (
        ("road_safety", "Satellite road-safety specialized prompts"),
        ("greenery", "Satellite greenery specialized prompts"),
    ):
        parts.extend([f"### {label}", ""])
        for stage in SATELLITE_SPECIALIZED_STAGES:
            parts.extend([prompt_details(group, stage), ""])

    parts.extend([
        "## LLM-as-judge prompts and protocol",
        "",
        "Benchmark judging compares two images in a fixed order: the "
        "**original/reference image first**, followed by the **edited/output "
        "image**. The three final criteria are intentionally split into two "
        "judge requests because policy preservation and output naturalness test "
        "different failure modes.",
        "",
        "| Request | Scores returned | Role in the tracked evaluator |",
        "|---|---|---|",
        "| Policy-preservation judge | `policy_preservation` | Computed separately; `qwen3vl_evaluate.py` reads this existing score from its input |",
        "| Revised Qwen3-VL judge | `visual_quality`, `scene_realism` | Called once per image pair by the tracked evaluator |",
        "",
        markdown_details(
            "Policy-preservation judge prompt (complete)",
            fenced(judge["policy_prompt"]),
        ),
        "",
        markdown_details(
            "Qwen3-VL visual-quality and scene-realism judge prompt (complete)",
            fenced(judge["revised_prompt"]),
        ),
        "",
        "### Revised Qwen3-VL request details",
        "",
        "| Setting | Value |",
        "|---|---|",
        "| Script | [`llm_judge/qwen3vl_evaluate.py`](../llm_judge/qwen3vl_evaluate.py) |",
        "| Default provider / endpoint style | OpenRouter / Chat Completions |",
        "| Default model | `qwen/qwen3-vl-32b-instruct` |",
        "| API-key environment variable | `OPENROUTER_API_KEY` |",
        "| Image order | Original/reference, then edited/output |",
        "| Image preprocessing | Preserve aspect ratio; resize only when the longest side exceeds 1024 px; JPEG quality 92 |",
        "| Temperature | `0.0` |",
        "| Maximum output tokens | `300` |",
        "| Structured output | Strict JSON Schema |",
        "| Default retries / workers | 4 retries / 1 worker |",
        "",
        "The exact structured-output schema is:",
        "",
        fenced(json.dumps(judge["schema"], indent=2), "json"),
        "",
        "The evaluator validates both scores as integers from 1 through 10, "
        "records input/output/total token usage and errors, resumes from an "
        "existing output CSV, and calculates `llm_judge_avg` as the arithmetic "
        "mean of `policy_preservation`, `visual_quality`, and `scene_realism`. "
        "It does **not** silently replace or recompute the supplied "
        "`policy_preservation` score.",
        "",
        "Print the exact active revised judge prompt without making an API request:",
        "",
        fenced("python llm_judge/qwen3vl_evaluate.py --print_prompt", "shell"),
        "",
    ])
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
