#!/usr/bin/env python3
"""Build docs/PROMPTS.md from VIDA-GEO's committed prompt sources."""
from __future__ import annotations

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROMPTS_ROOT = ROOT / "configs" / "prompts"
OUTPUT = ROOT / "docs" / "PROMPTS.md"
GROUPS = (
    ("gsv", "Google Street View domains"),
    ("road_safety", "Satellite road-safety domain"),
    ("greenery", "Satellite greenery domain"),
)
STAGES = (
    "planner",
    "planner_epoch",
    "suggestion_gemini",
    "suggestion_flux",
    "mask_qc",
    "edit_qc",
)


def fenced(text: str, language: str = "text") -> str:
    return f"```{language}\n{text.rstrip()}\n```"


def markdown_details(summary: str, body: str) -> str:
    return (
        "<details>\n"
        f"<summary>{summary}</summary>\n\n"
        f"{body.rstrip()}\n\n"
        "</details>"
    )


def literal_string(node: ast.AST) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "strip"
    ):
        return literal_string(node.func.value).strip()
    raise ValueError(f"Unsupported string expression: {ast.dump(node)}")


def policy_system_prompt() -> str:
    source = ROOT / "vida_geo" / "agents" / "policy.py"
    tree = ast.parse(source.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "_SYSTEM_PROMPT"
            for target in node.targets
        ):
            return literal_string(node.value)
    raise RuntimeError(f"_SYSTEM_PROMPT not found in {source}")


DYNAMIC_USER_MESSAGES = {
    "Initial planner": """Identify exactly 4 regions to {direction} the perceived {score_key}. Respond with JSON only.""",
    "Later-epoch planner": """Epoch {epoch_number}: find NEW regions to {direction} {score_key}. Respond with JSON only.""",
    "Policy review": """Target metric: {score_key} (goal: {goal})
Scene: {global_scene_description}

{region_count} region(s) to assess:

REGION 1:
  region_id: {region_id}
  label: {label}
  description: {description}
  edit_type: {replace_or_remove}
  feature_type: {feature_type}

... one block per region ...

Assess each region's physical plausibility. JSON only.""",
    "Generation suggestion": """Region being edited: {region_label}
Region description: {region_description}

{optional current score, prior failures, used prompts, policy hint, and phase context}

Write {GEMINI|FLUX} editing prompt(s) for this region. JSON only.""",
    "Mask QC": """The mask should cover: {region_label}
Description: {region_description}
Judge how well the mask matches this target. Respond with JSON only.""",
    "Edit QC": """{image-order explanation; masked or full-image}
Edit description: {edit_description}
Target metric: {score_key} (goal: {increase|reduce} the {score_key} score).
Region policy constraint: {constraint or "None specified."}
{scene elements elsewhere that must not be damaged, or "None specified."}
Score this edit. Respond with JSON only.""",
}

GEMINI_MASKED = """You will receive two images:
1) The original image to edit.
2) A mask. White pixels indicate the ONLY region you are allowed to change. Black pixels must remain EXACTLY the same.

Task: {suggested_edit_prompt}

Rules:
- ONLY modify pixels inside the white mask region.
- Do not change anything outside the white region.
- Blend naturally with the scene.
- Do not add text, labels, watermarks, or borders."""

GEMINI_MASKLESS = """Edit this image according to the following instruction:

{suggested_edit_prompt}

Rules:
- Keep everything else the same.
- Blend naturally with the scene.
- Do not add text, labels, watermarks, or borders."""

GEMINI_REMOVE = """Remove the {region_label} from the highlighted/masked area. Fill naturally with the surrounding background — match textures, lighting, and perspective seamlessly."""


def build() -> str:
    parts = [
        "# VIDA-GEO Pipeline Prompt Reference",
        "",
        "This page documents every natural-language prompt sent by the VIDA-GEO "
        "agent pipeline. Stable system prompts are reproduced verbatim from "
        "[`configs/prompts/`](../configs/prompts/); runtime-only user messages "
        "are shown with `{placeholders}`. Scoring and point-coordinate service "
        "calls are also listed for completeness, although they do not contain "
        "natural-language prompts.",
        "",
        "> This file is generated by `python scripts/build_prompt_reference.py`. "
        "Edit the source templates or generator rather than editing this page directly.",
        "",
        "## API-call inventory",
        "",
        "| Stage | API/model role | Images supplied | Prompt source |",
        "|---|---|---:|---|",
        "| Baseline and candidate scoring | Domain scorer service | 1 | No natural-language prompt |",
        "| Initial planning | Reasoning VLM | 1 | Domain `planner.txt` plus dynamic user message |",
        "| Later-epoch planning | Reasoning VLM | 1 | Domain `planner_epoch.txt` plus attempt history |",
        "| Policy review | Reasoning VLM | 1 | Shared policy system prompt plus all planned regions |",
        "| Text segmentation | LISAt or SAM3 | 1 | Planner-derived concrete `seg_keyword` and synonyms |",
        "| SAM fallback | SAM | 1 | Point coordinates and labels only; no text prompt |",
        "| Generation suggestion | Reasoning VLM | 1 or 2 | Domain `suggestion_gemini.txt` or `suggestion_flux.txt` |",
        "| Gemini generation | Gemini image editor | 1 or 2 | Suggested edit wrapped in masked or maskless instructions |",
        "| FLUX generation | FLUX Fill service | image + mask | Suggested visual-result prompt is passed directly |",
        "| Mask QC | Reasoning VLM | original + mask | Domain `mask_qc.txt` plus target description |",
        "| Edit QC | Reasoning VLM | original + edit [+ mask] | Domain `edit_qc.txt` plus edit and preservation constraints |",
        "",
        "All reasoning calls use the shared OpenRouter transport in "
        "[`vida_geo/llm/openrouter.py`](../vida_geo/llm/openrouter.py). "
        "Image generation uses [`vida_geo/tools/gemini.py`](../vida_geo/tools/gemini.py) "
        "or the FLUX service.",
        "",
        "## Runtime user-message templates",
        "",
    ]
    for name, template in DYNAMIC_USER_MESSAGES.items():
        parts.extend([
            f"### {name}",
            "",
            fenced(template),
            "",
        ])

    parts.extend([
        "### Text-segmentation request",
        "",
        "LISAt and SAM3 receive the planner's refined one- or two-word "
        "`seg_keyword` (for example, `road`, `parking lot`, `street lamp`, or "
        "`tree canopy`). VIDA-GEO may retry up to four concrete synonym variants. "
        "This request contains no separate system prompt.",
        "",
        "## Shared policy prompt",
        "",
        "Source: [`vida_geo/agents/policy.py`](../vida_geo/agents/policy.py)",
        "",
        markdown_details(
            "Policy system prompt (verbatim)",
            fenced(policy_system_prompt()),
        ),
        "",
        "## Image-editor request wrappers",
        "",
        "The suggestion agent first produces `{suggested_edit_prompt}` using one "
        "of the domain templates below. The selected prompt is then wrapped as follows.",
        "",
        markdown_details("Gemini masked-edit instruction", fenced(GEMINI_MASKED)),
        "",
        markdown_details("Gemini maskless instruction", fenced(GEMINI_MASKLESS)),
        "",
        markdown_details("Gemini removal instruction (GSV only)", fenced(GEMINI_REMOVE)),
        "",
        "FLUX receives the selected visual-result prompt directly, along with the "
        "cropped ROI image and mask.",
        "",
        "## Stable domain system prompts",
        "",
        "Template variables are substituted at runtime:",
        "",
        "- `$metric`: the domain score key.",
        "- `$direction`: `increase` or `reduce`, derived from the registry and goal.",
        "- `$metric_description` and `$edit_examples`: domain hints from "
        "[`configs/domains.yaml`](../configs/domains.yaml).",
        "- `$score_ctx`, `$previous_attempts`, `$tried_coords`, and `$phase_ctx`: "
        "current-score and orchestration history.",
        "",
    ])

    for group, label in GROUPS:
        parts.extend([f"### {label}", ""])
        for stage in STAGES:
            path = PROMPTS_ROOT / group / f"{stage}.txt"
            source = f"../configs/prompts/{group}/{stage}.txt"
            parts.extend([
                markdown_details(
                    f"<code>{stage}</code> - <a href=\"{source}\">source</a>",
                    fenced(path.read_text(encoding="utf-8")),
                ),
                "",
            ])

    parts.extend([
        "## Qwen3-VL benchmark-evaluation prompt",
        "",
        "The LLM-as-judge evaluation is separate from the editing pipeline. Its "
        "complete visual-quality and scene-realism prompt is embedded in "
        "[`llm_judge/qwen3vl_evaluate.py`](../llm_judge/qwen3vl_evaluate.py). "
        "Print the exact prompt without making an API request:",
        "",
        fenced("python llm_judge/qwen3vl_evaluate.py --print_prompt", "shell"),
        "",
    ])
    return "\n".join(parts).rstrip() + "\n"


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
